version: "3.9"

services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root
    ports:
      - 8081:8080
      - 50001:50000
    container_name: jenkins
    volumes:
      - ./jenkins_data:/var/jenkins_home