version: '3.9'

services:
  app:
    build: ./app
    image: flask_app_pdris
    container_name: flask_app
    ports:
      - 5000:5000
    volumes:
      - ./app:/app
  ansible:
    build: ./ansible
    command: ansible-playbook DockerPlaybook.yml -i inventory.yml
    volumes:
      - /var/run/docker.sock://var/run/docker.sock
      - ./app:/app
