services:
   redis:
     image: redislabs/redismod
     container_name: redis
     ports:
       - "6379:6379"
   flask:
        build: .
        container_name: flask
        ports:
            - "5000:5000"
        volumes:
            - .:/flask_redis_app
        depends_on:
            - redis